export const data = [
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Swisher Sweets LTO',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_SwisherSweets_LTO.png',
    group: 'Cigars & Cigarellos',
    itemImage: 'https://swisher.com/wp-content/uploads/2020/03/Swisher_CC_LTO_640x640.png',
    desc: 'Where will Swisher take you next? Limited Edition hybrid blends push innovation to the next level. Our bold and unique cigarillos offer the perfect mix of sweet and satisfying. One thing’s for sure — enjoy ‘em before they’re gone.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'BLK',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_BLK.png',
    group: 'Cigars & Cigarellos',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/05/swisher_cc_blk_640x640.png',
    desc: 'Hand-selected pipe tobacco meets a hands-down unique experience. BLK combines high quality and convenience in unforgettable blends, from the easy draw of the signature black tip to the intense aroma and smooth taste. Swisher Sweets BLK delivers a sleek pipe smoke that’s anything but ordinary.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'LEAF',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_LEAF.png',
    group: 'Cigars & Cigarellos',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_CC_Leaf_640x640.png',
    desc: 'Chance favors the bold. So claim your ultimate reward — the satisfying smoke of a Swisher Sweets Leaf cigar. A Connecticut broadleaf natural wrapper is the perfectly imperfect backdrop for a slow burn that packs a punch. Whether you’re in the mood for complex, rich, or something in between, you’ll find a Sweets Leaf that sets the tone, any time, any place.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Gold River',
    brandLogo: 'https://swisher.com/wp-content/uploads/2020/06/Swisher_LogoGrid_Logo_Smokeless_GoldRiver-1.png',
    group: 'Smokeless',
    itemImage: 'https://swisher.com/wp-content/uploads/2020/03/Swisher_Smokeless_GoldRiver_640x640.png',
    desc: 'Gold River is a unique snuff that is “A Cut Above.” The easy grip and twist lid is perfect for the on-the-go user and as a western cut, Gold River is a longer cut, easier to pack and a bold tobacco blend that is sure to satisfy. If you like “Awesome,” rush to Gold River!',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Creek',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/09/Swisher_LogoGrid_Logo_Smokeless_Creek.png',
    group: 'Smokeless',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/09/Swisher_Smokeless_Moist_Creek_640x640.png',
    desc: 'Whether it’s bold taste, fresh cuts or quality blends, CREEK delivers! If your adventure is hunting, fishing or just getting out and going, there is nothing better than discovering a new secret spot. Explore the boundaries and experience the finest blends of 100% American grown tobaccos with CREEK.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Kayak',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/09/Swisher_LogoGrid_Logo_Smokeless_Kayak.png',
    group: 'Smokeless',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/09/Swisher_Smokeless_Moist_Kayak_640x640.png',
    desc: 'With updated packaging, Kayak is Always Ready to satisfy! Activate your senses with the finest quality tobaccos grown in the U.S.A. This moist snuff is always ready with great taste at the right price. A lineup that includes a variety of tastes and cuts means every customer will find something that satisfies.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Swisher Sweets',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_SwisherSweets.png',
    group: 'Filtered Cigars',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/05/swisher_filtered_sweets_640x640.png',
    desc: 'Swisher Sweets Little Cigars combine exciting blends with filtered tips to balance the perfect amount of sweet with just the right punch. Don’t let their size fool you, these “Littles” are fully loaded with the tastes you crave. Try these big tastes on for size.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'Santa Fe',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_Filtered_SantaFe.png',
    group: 'Filtered Cigars',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/05/swisher_filtered_santa-fe_640x640.png',
    desc: 'Yes, you can have it all. A filtered cigar with bold taste and at an everyday low price. Choose from a wide range of blends, all with the quality, consistency and value that are uniquely Santa Fe.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    brandTitle: 'King Edwards',
    brandLogo: 'https://swisher.com/wp-content/uploads/2019/05/Swisher_LogoGrid_Logo_KingEdward.png',
    group: 'Filtered Cigars',
    itemImage: 'https://swisher.com/wp-content/uploads/2019/05/swisher_filtered_king-edward_640x640.png',
    desc: 'Tobacco royalty, and for good reason. Experience why King Edward has reigned over the industry for over a century with no signs of slowing down — taste, quality and convenience. With every draw, King Edward cigars carry on a long-standing tobacco tradition. Hail to the King of classic with filtered cigars in distinct blends.',
    inventory: Math.floor(Math.random() * 10) + 1,
    price: Math.floor(Math.random() * 5) + 1,
  }
]